const ranks={
initiate:{title:"1 - Initiate",description:"The Embalmer checks the Initiate’s arm, and there it is, the mark of Anubis: an eczema where the Finger of Anubis had scratched the skin the day before. The Initiate leaves his old life behind and joins the Embalmer. His first journey leads him to the threshold of his own death. Face to face with Anubis and Ammit, the devourer of souls, he bargains for his life. He rises from the crypt, profoundly changed. The tattoo on his body hurts: it shows seven Circles. He’s now an Anubian, the soul of Africa.",fields:[["Prerequisite","Mark of Anubis"],["Result","Seven concentric Circles show on the Initiate’s belly. He gets +1D on all Action rolls against the Raze. He is a wanderer between worlds, exploring humankind, the ancestors, nature, and the fringes of the Psychovores. No African would refuse him food or drink. It is said that everything that an African does for an Initiate will be repaid hundredfold by the ancestral spirits."],["Equipment","-"]]},
enchanter:{title:"2 - Enchanter",description:"He holds the first canopic jar, feels the cold. He puts away the jackal’s-head-shaped lid and drinks. His Embalmer tells him that he is now an Enchanter. As such, he communicates with the land to appease the spirits’ and ancestors’ fury against life in general. He teaches the traditions to the Scourgers, gives them advice and comforts their souls. Without his permission, no well is dug, no marriage takes place. One day, a Hogon will ask him to choose.",fields:[["Prerequisite","PSY+Faith 6 or PSY+Willpower 6; INT+Legends 6; Renown 1"],["Result","The Enchanter teaches the people the old rites and counsels them in day-to-day affairs: all Backgrounds with the exception of Resources also apply towards Neolibyans, Scourgers, African Scrappers, and Clanners from African Clans. The same is true for all higher ranks. With every transformation, the Raze resistance grows: +2D on Action rolls to fending it off."],["Equipment","Anubis mask; soul stones (tools of superstition: +1D Charisma when trying to influence an African)"]]},
embalmer:{title:"3 - Embalmer",description:"The Embalmer has knowledge about spirits, ancestors, and death and knows how to use it. The Scourgers obey him, and young Anubians join him, searching for wisdom and transformation. It is said he can contact the spirits of the deceased and speaks in their stead. He can actually interfere with the ancestors’ whisperings: he opens himself to the Psychovores and lets them carry away his emotions. The next transformation lets him rise as a Soul Seer.",fields:[["Prerequisite","CHA+Expression 6; INT+Legends 7; INS+Empathy 7; Renown 2"],["Result","The Anubian can now interfere with the Psychovore Aethyr and thus influence the people around him through the whispering of the ancestors. He is, however, a slave of nature: the emotions generated are tied to his strongest Attribute. If it’s BOD the Africans feel stronger and healthier, if it is PSY they feel stronger of will, if it is INS they feel their primal nature and give in to it. Embalmers take in Initiates and teach them until they become Enchanters. All of these Initiates feel obliged to their Embalmer until the end of their days and count as his allies ((+1) Allies)."],["Equipment","Finger of Anubis (a sharpened bone to scratch Initiates’ skin with)"]]},
healer:{title:"3 - Healer",description:"The Healer knows a lot about earth, herbs, and potent waters. From them, he mixes concoctions to take the pain from the Scourgers and keep the Neolibyans healthy. But the really potent medicines are made by catalyzing Duat fruit. Over the years, the Healer perfects his body. He knows the amounts and ingredients he has to ingest to reach a desired effect. He also produces the legendary Marduk oil that negates the Pheromancers’ beguiling scent. Soon, the villagers will claim that he has magical powers. It is time to transform into a Hecatean.",fields:[["Prerequisite","BOD+Toughness 8; INT+Medicine 6; INT+Focus 6 or INS+Primal 6; Authority 2"],["Result","A Healer harvests earths, herbs, and potent soil from nature and Duat fruit in the Psychovores. When he needs other Anubians to attain some medicine for him, he gets a (+2) bonus on Resources. He can eat Duat fruit without the Raze consuming him. He has to make an Action roll on BOD+Toughness, though, (Difficulty = level of the Duat fruit) to start the catalysis. The level also determines the time that the Healer is suspended in a coma. The Anubian awakens one day earlier per Trigger, but always remains in catalysis for at least one hour. Resistance against Psychovores: +3D to fending off the Raze."],["Equipment","Crucible; healing earths"]]},
sickle:{title:"3 - Sickle",description:"Anubian Sickles accompany the Scourgers into the northern lands, are the Neolibyans’ advisors and guards. They feel the Psychonauts’ weak spots within themselves. They feel the corresponding Chakra bleed dry. They feel the emptiness. They want to get rid of it. Armed with a Khopesh, they are the perfect weapons against the Aberrants. With only a few cuts aimed at the Psychonaut’s singular Chakra, they slice through his Thread of Life.",fields:[["Prerequisite","BOD+Melee 6; PSY+Reaction 6; Renown 2; Network 2"],["Result","Gets the Potential “Eye of Horus” at level 1. A pack of Scourgers accepts the Anubian as a fighter, and he may challenge the strongest enemy even before the Simba. However, he can also reject to do so without losing honor. The Simba will be grateful. Resistance against Psychovores: +3D to fending off the Raze."],["Equipment","Khopesh"]]},
soulseer:{title:"4 - Soul Seer",description:"Anubis is a principle. The Anubian has understood this. To the people, he’s a judge and master of secrets. The Psychovores shrink back from his thoughts, withering and dying. But at his behest, they also activate their defense mechanisms: they spit thorns, and fruits detonate into clouds of splinters. They bring the Raze to his enemies.",fields:[["Prerequisite","CHA+Expression 10; INT+Science 7; Secrets 3; Renown 3"],["Result","Through will alone, the Anubian creates a passage through the Psychovores—and they make way for him and his companions. Not for his enemies, however: they shoot thorns, or fruit falls from shrubs and explodes into highly poisonous clouds. The Psychovores attack with their Level and bring the Raze. Psychovores with a Level of (5+) resist the Soul Seer. The Anubian develops advanced resistance against the Raze: +4D against its effects. Tripol’s Bank of Commerce has Soul Seers measure their business partners’ Thread of Life. With an Action roll on INS+Empathy (4), the Soul Seer goes deep inside the life and deeds of the person he looks at."],["Equipment","-"]]},
hecatean:{title:"4 - Hecatean",description:"A Hecatean can repair a person’s torn Thread of Life in the Imiut skin. He has elevated the catalysis to a new level. His skin changes color, sometimes smelling lovely, sometimes bringing the Raze through a simple touch. He is able to reconfigure his metabolism and keep up this change for minutes or even hours.",fields:[["Prerequisite","BOD+Toughness 10; INT+Focus 8 or INS+Primal 8; INT+Science 6; Authority 3"],["Result","The Hecatean is the lord of death. If he sews a freshly deceased into a Gendo skin and performs the Imiut ritual, he can repair the torn Thread of Life (see “Patched Up” in Chapter 7, “Battle”). He can restructure his metabolism and raise Attributes once per day: to do so, he rolls INT+Focus or INS+Primal against the score of the Attribute in question. He can use the Triggers to extend the time and/or score: (1) Trigger brings (1) minute of duration or (+1) to the Attribute. It can even surpass the limit of (6) in this manner. Resistance against Psychovores: +4D to fending off the Raze."],["Equipment","Duat Blood (level 1)"]]},
ammit:{title:"4 - Ammit",description:"Standing next to Anubis, Ammit devours the hearts found lacking during the weighing. Anubians following in this tradition use their names like a weapon. They feel every falseness, divine every lie, are in tune with people, Psychonauts, and Psychovores. They judge Africans and Europeans alike, are the shadows in the night and the lightning bolt by day.",fields:[["Prerequisite","BOD+Athletics 6; BOD+Melee 10; PSY+Faith 6 or PSY+Willpower 6; Renown 5; Network 3"],["Result","An Ammit looks into the heart of a person: in the Psychovores’ area of influence, he gets +2D on any social interaction (all Charisma Action rolls, as well as PSY+Domination) and can also add his Renown Background as dice to social Action rolls. He knows the weak spots of all creatures: every hit with a weapon causes Ego Damage equal to the number of Triggers rolled in addition to the physical Damage. Resistance against Psychovores: +4D to fending off the Raze."],["Equipment","Ammit sickle"]]},
hogon:{title:"5 - Hogon",description:"The Hogons move in the third Circle – the last one that Anubians outside of Cairo get to see. Like ships they cut through the sea of Psychovores, yet even they have to turn around when reaching the barrier around Cairo. In the hidden crypts on the border of this barrier, they find the canopic jars of the jackal and the scrolls of wisdom. Their knowledge of anatomy, biochemistry, and the conscious mind keeps growing.",fields:[["Prerequisite","INT+Medicine 10; INT+Science 8; INS+Empathy 8; Secrets 5"],["Result","The Hogon takes off the mantle made of superstition and folklore: he faces every attempt to influence him based on superstition with +4D. His resistance against the Raze rises to +6D. Only the Psychovores in the Dhoruba and all around Cairo still resist him. A Hogon prepares for his way to Cairo. He knows the secret caches of the canopic jars and selects young Anubians for the catalysis."],["Equipment","-"]]}
};
const potentials=[
["I. Sekhmet’s Slumber","Anubians","The lion-headed god covers the dead body with her paws so that neither demons nor the vigilant gaze of Anubis can see it.","The Anubian falls into a coma indistinguishable from death that cannot be interrupted once it begins. After (4) days, he wakes up fully healed. The number of days is reduced by (1) per Potential level. This Potential can be combined with Mercy of Anubis."],
["II. Navel of Nefertem","Anubians","And so the cusps of the blue lotus rose up from the primal waters, blooming in cruel beauty into a strange world, and they knew Nefertem as their god. The lotus, the Hogons whisper, will not devour those who walk in the god’s shadow.","The Anubian develops a resistance to the Psychovores, which also influences their catalysis. The Difficulty of defense against the Raze and catalysis of medicine decreases by (1) per Potential level."],
["III. Eye of Horus","Anubians","The falcon-headed god rises into the air, and his wing tips stretch to the ends of the earth. His unblinking black eyes—the moon eye and the sun eye—pick up even the smallest ripples of the wave.","Anubians using the Eye of Horus feel disturbances of the wave across vast distances (level 1: up to 100 m; level 2: up to 1 km; level 3: up to 10 km). Without fail they lead the way to Psychonauts, and can see the gleaming network of force lines on the body of the Aberrant. They gain (1) Trigger per Potential level when attacking Psychonauts, Spore Beasts, and Leperos."],
["IV. Mercy of Anubis","Anubians","The wave breaks, but the Anubian isn’t granted the deep fall into the eternity of Anubis’ realm. His time has not come yet, and he can muster up one last desperate attempt to spite his foes.","If the Anubian takes more than his maximum Trauma Damage and falls unconscious, he can still rise again and fight on for (1) Combat Round per Potential level until he finally collapses dead. Any weapons the Anubian wields gain the Terrifying Quality, with the rating equal to the Potential level x2."],
["V. Ammit’s Feast","Anubians, Primal","All mental barriers break, and the devourer of souls weaves her way into the Anubian’s mind, corrupting him, driving him into an abyss of ancient hatred.","If an Anubian achieves (2) Triggers on a melee attack, they can fly into a frenzy. Anubians imbued by Ammit can no longer make Active Defense rolls. For every Combat Round that the Anubian remains frenzied, his Attack rolls gain +1D and his Damage is increased by (1), up to the Potential Level. It must be reactivated with (2) Triggers each Round and costs (1) Flesh Wound for every Round after the first."],
["VI. Gaze of Fate","Anubians","Not even the gods dare to look into the future, for they fear the demons beyond the frame of the world, lurking behind Horus’ wing tips.","Once per month the Anubian may foresee a limited period of the imminent future and adds +2D to the foreseen Action per Potential level. Level 1: Seconds. Level 2: Minutes. Level 3: Hours."],
["VII. Ancestral Stare","Anubians, INS+Perception 10","Once one crosses into the spirit world, knowledge is ubiquitous. Every stone, every creature, and every gust of wind tells a story – an open mind is necessary to understand these quiet whispers.","Once per day, with a roll on INS+Perception (6), the character receives a cryptic hint concerning a future event. The Difficulty is lowered by (1) per Potential level. A character can further roll INS+Empathy (3) to decipher the connotation to be either positive or negative."],
["VIII. Embrace of Apophis","Anubians, Primal, BOD+Brawl 6","Some Anubians practice a form of martial arts that blocks the energy flow in an enemy’s body, rendering them incapable of fighting.","A practitioner’s Passive Defense is raised by (1) per Potential level. Kicks, holds and blows are considered Aimed Attacks at (+4) Difficulty, reduced by (1) per Potential level. Blows and kicks gain Dazed (4) and Smooth Running (2T); chokeholds gain Dazed (6) and Entangled (4)."],
["IX. The Darkest Heart","Anubians, Focus","Death is a realm of darkness. An Anubian who drowns his heart in this very darkness, achieves control over his emotions in battle, and places his fate into the hands of Anubis.","The Anubian spends (3) Ego Points and enters (3) Rounds of meditation. He is immune to all forms of mental influence from Psychonauts for a number of Rounds equaling his Potential level, then adds (1) Success per Potential level to Mental Defense rolls for the remainder of the scene or combat."],
["X. Chill of Death","Anubians, Primal","Channeling the energies of the afterlife, Anubians exceed the limitations of their mortal bodies. The closer they are to their own death, the more ferocious their attacks become.","For each point of Trauma suffered in combat, the Anubian adds (1) Damage to all following Brawl and Melee attacks. The bonus cannot exceed the Potential level."],
["XI. Afterlife","Anubians","Anubis’ realm is a deep well of knowledge. Those who travel through the afterlife during Sekhmet’s Slumber reap incredible wisdom and return to the world of the living with profound insight.","Once per month per Potential level, if the Anubian enters Sekhmet’s Slumber while suffering Trauma, he can reap Experience points equal to either his Focus or Primal rating."],
["XII. Soul Drain","Anubians","The body is the fortress of the soul, yet it is the soul that moves the body. One cannot exist without the other.","A Focus oriented Anubian may trade (1) self-inflicted Flesh Wound for (1) Ego Point. A Primal oriented Anubian may spend (1) Ego Point to heal (1) Flesh Wound. In both cases they exchange (1) point per Round and cannot trade more than (2) points a day per Potential level."],
["XIII. Coils of Set","Anubians, Primal, BOD+Brawl 6, INS+Perception 6","Set guides the strike of an Anubian in battle, points him to the weakest spot in the opponent’s mortal shell, and entangles him so he cannot flee.","The Anubian attacks with BOD+Brawl as an Aimed Attack at (+4) Difficulty. If successful, the opponent suffers -1D per Potential level to following Attack and Defense rolls for a number of Combat Rounds equal to the Potential level. Movement is reduced by (1) meter per point of Damage. Each Potential level lowers the Aimed Attack Difficulty by (1)."],
["XIV. Sobek’s Patience","Anubians, Focus","Sobek, the great crocodile, knows when to raise himself from the deep waters to bite down on his prey. He is the god of deliberate patience, biding his time for the ultimate strike.","For every (1) Combat Round the Anubian delays expending Ego when rolling Initiative, he raises the maximum Ego he can spend at once during the following Round by (1), above the maximum of (3). He can delay a maximum number of Combat Rounds equal to his Potential level."],
["XV. Fortitude of Osiris","Anubians, Focus, BOD+Toughness 8, PSY+Faith/Willpower 8","Pain is nothing but a glimpse of the afterlife. Those who have traveled Anubis’ realm aren’t afraid of it anymore.","For every Potential level, the Anubian can delay pain and Damage taken by (1) Combat Round, up to a maximum of (3). This includes all penalties suffered from Trauma Damage."]
].map(([title,pre,effect,rules])=>({title,fields:[["Prerequisite",pre],["Effect",effect],["Rules",rules]]}));
const equipmentGroups=[
{title:"Talismans",items:[
{title:"Anubis Mask",description:"When an Anubian wears this mask and has painted his body black with tree resin, he symbolically becomes Anubis. He is untouchable and, according to legend, has the abilities of a god. This mask is used for all important rites.",fields:[["Specialty","The wearer of the mask gets +1D to every social interaction with other Africans."],["Encumbrance","-"],["Tech","I"],["Value","200"],["Resources","-"]]},
{title:"Anubis Finger",description:"The bone is as long as a man’s lower arm and adorned with engraved circles and spirals. It shines as if polished by the thousands of hands it’s gone through. One end is sharpened and yellowed. The bone looks like a prehistoric weapon, and in fact it hails from the time of the first people, though it was never used in combat.",fields:[["Specialty","The fewer circles are painted onto an Anubian’s body, the faster the mark becomes visible. On a potential Initiate it takes over 12 hours to show, while on a Hogon it blossoms in seconds."],["Encumbrance","-"],["Tech","I"],["Value","9000"],["Resources","-"]]},
{title:"Soul Stones",description:"The Dhoruba asteroid caused molten rock to fall from the sky. It cooled and rained down on earth as glass drops. Before the Psychovores covered the Dhoruba, the Africans collected the black glass. They thought it held the souls of those the asteroid had burned and blown away.",fields:[["Specialty","A believer can be impressed by the stones. The Anubian gets +1D to social interactions with him. The stones must be visible to have this effect."],["Encumbrance","-"],["Tech","I"],["Value","800"],["Resources","1"]]}
]},
{title:"Medical",items:[
{title:"Crucible",description:"In these pitch black stone vessels the Anubian healers grind earths and plants and mix them with fat to produce ointments and potions. It is said that the crucibles are made of meteorite stone.",fields:[["Specialty","The stuff from which the crucibles are made is antibacterial and antimycotic: the Anubian gets +1D on the production of drugs or poisons."],["Encumbrance","-"],["Tech","I"],["Value","150"],["Resources","2"]]},
{title:"Duat Fruit",description:"They are gathered deep in the Psychovores and carry the Raze. Anubians chew the splintery Duat fruit to start a catalysis, a very dangerous procedure that only Healers and Hecateans dare to attempt.",fields:[["Specialty","Levels 1-6 represent potency and depth within the Psychovores. An Anubian can catalyze fruit up to a level equaling his rank without danger."],["Value","200 x Level"],["Resources","1 / 2 / 3"]]},
{title:"Duat Blood",description:"If an Anubian has survived the catalysis of a Duat fruit, a process that brings them face to face with Anubis in a near-death coma, the source of all life boils in his veins.",fields:[["Specialty","Duat Blood is considered a general antidote with a Potency equaling its level."],["Effect","Panacea: resistance roll +1S x Level"],["Value","300 x Level"],["Resources","1 / 2 / 3"]]}
]},
{title:"Weapons",items:[
{title:"Khopesh",description:"According to myth, only the Khopesh chosen by Anubis can cut through a creature’s lifeline without tearing through meat and organs like the Scourgers do. The sword is brought into the land of the Crow mainly by the Anubian Sickles and Ammits to eradicate Psychonauts from the wave.",fields:[["Handling","-"],["Distance","1"],["Damage","6+F/2"],["Qualities","Special Damage (Psychonauts, +2)"],["Encumbrance","2"],["Tech","II"],["Slots","2"],["Value","1800"],["Resources","3"]]},
{title:"Ammit Sickle",image:"assets/ammit-sickle.webp",alt:"Ammit Sickle",description:"An Ammit sickle is even rarer than a Khopesh. According to legend, its blade was made from meteorite iron collected millennia ago from a crater in central Africa. The blades are pockmarked and black from age: only the edges are sharp. The faces show delicate patterns reminiscent of the contour lines on topographic maps.",fields:[["Handling","-"],["Distance","1"],["Damage","7+F/2"],["Qualities","Special Damage (Psychonauts, +3)"],["Encumbrance","2"],["Tech","II"],["Slots","2"],["Value","3200"],["Resources","6"]]}
]}];
const esc=v=>String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function renderRank(id){const r=ranks[id],d=document.querySelector("#rank-detail");d.innerHTML=`<p class="rank-kicker">SELECTED RANK</p><h3>${esc(r.title)}</h3><p>${esc(r.description)}</p><dl class="entry-fields">${r.fields.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join("")}</dl>`;document.querySelectorAll(".rank-node").forEach(b=>{let s=b.dataset.rank===id;b.classList.toggle("is-selected",s);b.setAttribute("aria-pressed",s)})}
function renderPotential(i){const p=potentials[i];document.querySelector("#potential-detail").innerHTML=`<p class="rank-kicker">SELECTED POTENTIAL</p><h3>${esc(p.title)}</h3><dl class="entry-fields">${p.fields.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join("")}</dl>`;document.querySelectorAll(".potential-select").forEach((b,j)=>b.classList.toggle("is-selected",i===j))}
function renderPotentials(){const l=document.querySelector("#potential-list");l.innerHTML=potentials.map((p,i)=>`<button class="potential-select" data-potential-index="${i}">${esc(p.title)}</button>`).join("");l.querySelectorAll("button").forEach(b=>b.onclick=()=>renderPotential(+b.dataset.potentialIndex));renderPotential(0)}
function renderEquipment(){document.querySelector("#equipment-groups").innerHTML=equipmentGroups.map((g,i)=>`<details class="equipment-group" ${i===0?"open":""}><summary><span>${esc(g.title)}</span><span class="equipment-count">${g.items.length} ENTRIES</span></summary><div class="equipment-group-body"><div class="equipment-grid">${g.items.map(x=>`<article class="reference-card equipment-card">${x.image?`<div class="equipment-art"><img src="${x.image}" alt="${x.alt}"></div>`:""}<h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><dl class="entry-fields compact-fields">${x.fields.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join("")}</dl></article>`).join("")}</div></div></details>`).join("")}
document.querySelectorAll(".rank-node").forEach(b=>b.onclick=()=>renderRank(b.dataset.rank));renderRank("initiate");renderPotentials();renderEquipment();
const navToggle=document.querySelector("#lorebook-nav-toggle"),sidebarScrim=document.querySelector("#sidebar-scrim");const setSidebar=o=>{document.body.classList.toggle("sidebar-open",o);navToggle?.setAttribute("aria-expanded",String(o))};setSidebar(matchMedia("(min-width: 761px)").matches);navToggle?.addEventListener("click",()=>setSidebar(!document.body.classList.contains("sidebar-open")));sidebarScrim?.addEventListener("click",()=>setSidebar(false));document.querySelectorAll('.lorebook-sidebar a[aria-disabled="true"]').forEach(a=>a.onclick=e=>e.preventDefault());