name: Import Hellvetic artwork

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/import-hellvetic-assets.yml"

permissions:
  contents: write

jobs:
  import-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          sudo apt-get update
          sudo apt-get install -y webp
      - name: Download artwork
        run: |
          curl -fL "https://lh7-rt.googleusercontent.com/slidesz/AGV_vUfDSSTJhPgwAFWTBWd_TYeRdw4e5NRCxqkZcc2QcA3YUOpe_VdY429ql2YCrfojgwfh1ydQYL15aFTa5pHS1kIJ2UtTiv2RwqZ-lSbbOpQn3FDsch9cdJyTD-AXWmqABeLMa-U2IYnslbsigy-sqZEAggl6-PY-bjyqppBGUe7V8fwMT5Y=s2048?key=XjseKAa0MKb2i9uOrDptiw" -o /tmp/hellvetic-main.png
          curl -fL "https://lh7-rt.googleusercontent.com/slidesz/AGV_vUc32UcjPhisrWpPrFxvBMskHdaTvGHl2B2Iezug_1j4w6JAJ1WMHeMVgzvX7ymso_gG__rQsB1jyhrzaYgVzHjFxhQ1pJalBOeY2wZsbVOYjHyZIDr0xrkTlD2UOMZmCgTNNrv4mZAuKNU4Tp_0oYOriOl8m8vhdgWbICgHAY_WD8P_NVM=s2048?key=XjseKAa0MKb2i9uOrDptiw" -o /tmp/hellvetic-radio.png
          curl -fL "https://lh7-rt.googleusercontent.com/slidesz/AGV_vUcaFaNlti5ZkOtJ2uzIqtm-0EPgftK7b2YPxRQDqJZA5GUJurRWT9f0odfM_I_BH-zrn9Exv7TES8JIZJGwJRlvXrt0ZVkyg-p_QD5THDp96B_Nm74kk81rJMFBlsLGirmUsiItGwka7tOeWm85otBrUZwyahp842VFIWjVW8u3ynC4=s2048?key=XjseKAa0MKb2i9uOrDptiw" -o /tmp/trailblazer.png
          curl -fL "https://lh7-rt.googleusercontent.com/slidesz/AGV_vUe8cIS5O3Aqs1tvviAsv_nJV0lJvAX2fdcSW5_pOviXX5kncdcoVpyIgnd2a3HKyguQEchZaZZtMxaVaipHZh0Vy9eUR5M8UyLrDf82X5wZjomTTvFstM_NUG23uCH7FZlWrzNgwU8uAERwpEt8hRczgZvihSUg8iMu5XfQocIsgrK9=s2048?key=XjseKAa0MKb2i9uOrDptiw" -o /tmp/tunnel-shield.png
          curl -fL "https://lh7-rt.googleusercontent.com/slidesz/AGV_vUc1fpb0wcRNigSnotFdvExJm4yBmlMJoCzuXFakPg9j9d2W6W7a-O-dxC09600GRkAAqqEvS4BI-gBiyGYJ4AwDJlAhA3lpyZuaMjll4iTIxgYrDUbNzHs09g2IJSoih9v-yrDY9VhKX7-AlameCvDMjAiBUL08rFpn9LDdPRiKOo2XILQ=s2048?key=XjseKAa0MKb2i9uOrDptiw" -o /tmp/hellvetics-logo.png
      - name: Convert and commit
        run: |
          cwebp -quiet -q 86 -alpha_q 100 /tmp/hellvetic-main.png -o assets/hellvetic-main.webp
          cwebp -quiet -q 86 -alpha_q 100 /tmp/hellvetic-radio.png -o assets/hellvetic-radio-beam.webp
          cwebp -quiet -q 88 -alpha_q 100 /tmp/trailblazer.png -o assets/trailblazer.webp
          cwebp -quiet -q 88 -alpha_q 100 /tmp/tunnel-shield.png -o assets/tunnel-shield.webp
          cwebp -quiet -lossless /tmp/hellvetics-logo.png -o assets/hellvetics-logo.webp
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/hellvetic-main.webp assets/hellvetic-radio-beam.webp assets/trailblazer.webp assets/tunnel-shield.webp assets/hellvetics-logo.webp
          git rm .github/workflows/import-hellvetic-assets.yml
          git commit -m "Add Hellvetic artwork"
          git push
